nb_data = [
    {
        "id": 1,
        "url": "https://netboxdemo.com/api/dcim/devices/1/",
        "display": "1701_CORE_SWITCH",
        "name": "1701_CORE_SWITCH",
        "display_name": "1701_CORE_SWITCH",
        "device_type": {
            "id": 3,
            "url": "https://netboxdemo.com/api/dcim/device-types/3/",
            "display": "S4028-ON",
            "manufacturer": {
                "id": 1,
                "url": "https://netboxdemo.com/api/dcim/manufacturers/1/",
                "display": "Dell",
                "name": "Dell",
                "slug": "dell",
            },
            "model": "S4028-ON",
            "slug": "s4028-on",
            "display_name": "Dell S4028-ON",
        },
        "device_role": {
            "id": 1,
            "url": "https://netboxdemo.com/api/dcim/device-roles/1/",
            "display": "Core Switch",
            "name": "Core Switch",
            "slug": "core-switch",
        },
        "tenant": {
            "id": 1,
            "url": "https://netboxdemo.com/api/tenancy/tenants/1/",
            "display": "Starfleet",
            "name": "Starfleet",
            "slug": "starfleet",
        },
        "platform": {
            "id": 1,
            "url": "https://netboxdemo.com/api/dcim/platforms/1/",
            "display": "Cumulus NOS",
            "name": "Cumulus NOS",
            "slug": "cumulus-nos",
        },
        "serial": "FCN12345",
        "asset_tag": None,
        "site": {
            "id": 1,
            "url": "https://netboxdemo.com/api/dcim/sites/1/",
            "display": "NCC-1701-D",
            "name": "NCC-1701-D",
            "slug": "ncc-1701-d",
        },
        "location": {
            "id": 1,
            "url": "https://netboxdemo.com/api/dcim/locations/1/",
            "display": "MDF Room",
            "name": "MDF Room",
            "slug": "mdf-room",
            "_depth": 0,
        },
        "rack": {
            "id": 1,
            "url": "https://netboxdemo.com/api/dcim/racks/1/",
            "display": "MDF_RACK1",
            "name": "MDF_RACK1",
            "display_name": "MDF_RACK1",
        },
        "position": 30,
        "face": {"value": "front", "label": "Front"},
        "parent_device": None,
        "status": {"value": "active", "label": "Active"},
        "primary_ip": {
            "id": 14,
            "url": "https://netboxdemo.com/api/ipam/ip-addresses/14/",
            "display": "2001:db8:1701::2/64",
            "family": 6,
            "address": "2001:db8:1701::2/64",
        },
        "primary_ip4": {
            "id": 16,
            "url": "https://netboxdemo.com/api/ipam/ip-addresses/16/",
            "display": "10.20.0.2/24",
            "family": 4,
            "address": "10.20.0.2/24",
        },
        "primary_ip6": {
            "id": 14,
            "url": "https://netboxdemo.com/api/ipam/ip-addresses/14/",
            "display": "2001:db8:1701::2/64",
            "family": 6,
            "address": "2001:db8:1701::2/64",
        },
        "cluster": None,
        "virtual_chassis": None,
        "vc_position": None,
        "vc_priority": None,
        "comments": "",
        "local_context_data": None,
        "tags": [],
        "custom_fields": {},
        "config_context": {},
        "created": "2019-12-22",
        "last_updated": "2019-12-22T20:09:27.354266Z",
    },
    {
        "id": 27,
        "url": "https://netboxdemo.com/api/dcim/devices/27/",
        "display": "1701_FW",
        "name": "1701_FW",
        "display_name": "1701_FW",
        "device_type": {
            "id": 6,
            "url": "https://netboxdemo.com/api/dcim/device-types/6/",
            "display": "PA-3020",
            "manufacturer": {
                "id": 5,
                "url": "https://netboxdemo.com/api/dcim/manufacturers/5/",
                "display": "Palo Alto",
                "name": "Palo Alto",
                "slug": "palo-alto",
            },
            "model": "PA-3020",
            "slug": "pa-3020",
            "display_name": "Palo Alto PA-3020",
        },
        "device_role": {
            "id": 3,
            "url": "https://netboxdemo.com/api/dcim/device-roles/3/",
            "display": "Firewall",
            "name": "Firewall",
            "slug": "firewall",
        },
        "tenant": {
            "id": 1,
            "url": "https://netboxdemo.com/api/tenancy/tenants/1/",
            "display": "Starfleet",
            "name": "Starfleet",
            "slug": "starfleet",
        },
        "platform": None,
        "serial": "",
        "asset_tag": None,
        "site": {
            "id": 1,
            "url": "https://netboxdemo.com/api/dcim/sites/1/",
            "display": "NCC-1701-D",
            "name": "NCC-1701-D",
            "slug": "ncc-1701-d",
        },
        "location": {
            "id": 1,
            "url": "https://netboxdemo.com/api/dcim/locations/1/",
            "display": "MDF Room",
            "name": "MDF Room",
            "slug": "mdf-room",
            "_depth": 0,
        },
        "rack": {
            "id": 1,
            "url": "https://netboxdemo.com/api/dcim/racks/1/",
            "display": "MDF_RACK1",
            "name": "MDF_RACK1",
            "display_name": "MDF_RACK1",
        },
        "position": 35,
        "face": {"value": "front", "label": "Front"},
        "parent_device": None,
        "status": {"value": "active", "label": "Active"},
        "primary_ip": {
            "id": 12,
            "url": "https://netboxdemo.com/api/ipam/ip-addresses/12/",
            "display": "2001:db8:1701::1/64",
            "family": 6,
            "address": "2001:db8:1701::1/64",
        },
        "primary_ip4": {
            "id": 10,
            "url": "https://netboxdemo.com/api/ipam/ip-addresses/10/",
            "display": "10.20.0.1/24",
            "family": 4,
            "address": "10.20.0.1/24",
        },
        "primary_ip6": {
            "id": 12,
            "url": "https://netboxdemo.com/api/ipam/ip-addresses/12/",
            "display": "2001:db8:1701::1/64",
            "family": 6,
            "address": "2001:db8:1701::1/64",
        },
        "cluster": None,
        "virtual_chassis": None,
        "vc_position": None,
        "vc_priority": None,
        "comments": "",
        "local_context_data": None,
        "tags": [],
        "custom_fields": {},
        "config_context": {},
        "created": "2019-12-22",
        "last_updated": "2019-12-22T19:47:50.028082Z",
    },
    {
        "id": 2,
        "url": "https://netboxdemo.com/api/dcim/devices/2/",
        "display": "1701_MDF_ACCESS-sw1",
        "name": "1701_MDF_ACCESS-sw1",
        "display_name": "1701_MDF_ACCESS-sw1",
        "device_type": {
            "id": 4,
            "url": "https://netboxdemo.com/api/dcim/device-types/4/",
            "display": "WS-C3850-48U",
            "manufacturer": {
                "id": 2,
                "url": "https://netboxdemo.com/api/dcim/manufacturers/2/",
                "display": "Cisco",
                "name": "Cisco",
                "slug": "cisco",
            },
            "model": "WS-C3850-48U",
            "slug": "ws-c3850-48u",
            "display_name": "Cisco WS-C3850-48U",
        },
        "device_role": {
            "id": 2,
            "url": "https://netboxdemo.com/api/dcim/device-roles/2/",
            "display": "Access Switch",
            "name": "Access Switch",
            "slug": "access-switch",
        },
        "tenant": {
            "id": 1,
            "url": "https://netboxdemo.com/api/tenancy/tenants/1/",
            "display": "Starfleet",
            "name": "Starfleet",
            "slug": "starfleet",
        },
        "platform": None,
        "serial": "FOC123451",
        "asset_tag": None,
        "site": {
            "id": 1,
            "url": "https://netboxdemo.com/api/dcim/sites/1/",
            "display": "NCC-1701-D",
            "name": "NCC-1701-D",
            "slug": "ncc-1701-d",
        },
        "location": {
            "id": 1,
            "url": "https://netboxdemo.com/api/dcim/locations/1/",
            "display": "MDF Room",
            "name": "MDF Room",
            "slug": "mdf-room",
            "_depth": 0,
        },
        "rack": {
            "id": 1,
            "url": "https://netboxdemo.com/api/dcim/racks/1/",
            "display": "MDF_RACK1",
            "name": "MDF_RACK1",
            "display_name": "MDF_RACK1",
        },
        "position": 25,
        "face": {"value": "front", "label": "Front"},
        "parent_device": None,
        "status": {"value": "active", "label": "Active"},
        "primary_ip": None,
        "primary_ip4": None,
        "primary_ip6": None,
        "cluster": None,
        "virtual_chassis": {
            "id": 1,
            "name": "1701_MDF_ACCESS-sw1",
            "url": "https://netboxdemo.com/api/dcim/virtual-chassis/1/",
            "master": {
                "id": 2,
                "url": "https://netboxdemo.com/api/dcim/devices/2/",
                "display": "1701_MDF_ACCESS-sw1",
                "name": "1701_MDF_ACCESS-sw1",
                "display_name": "1701_MDF_ACCESS-sw1",
            },
        },
        "vc_position": 1,
        "vc_priority": 15,
        "comments": "",
        "local_context_data": None,
        "tags": [],
        "custom_fields": {},
        "config_context": {},
        "created": "2019-12-22",
        "last_updated": "2019-12-22T17:16:34.942459Z",
    },
    {
        "id": 3,
        "url": "https://netboxdemo.com/api/dcim/devices/3/",
        "display": "1701_MDF_ACCESS-sw2",
        "name": "1701_MDF_ACCESS-sw2",
        "display_name": "1701_MDF_ACCESS-sw2",
        "device_type": {
            "id": 4,
            "url": "https://netboxdemo.com/api/dcim/device-types/4/",
            "display": "WS-C3850-48U",
            "manufacturer": {
                "id": 2,
                "url": "https://netboxdemo.com/api/dcim/manufacturers/2/",
                "display": "Cisco",
                "name": "Cisco",
                "slug": "cisco",
            },
            "model": "WS-C3850-48U",
            "slug": "ws-c3850-48u",
            "display_name": "Cisco WS-C3850-48U",
        },
        "device_role": {
            "id": 2,
            "url": "https://netboxdemo.com/api/dcim/device-roles/2/",
            "display": "Access Switch",
            "name": "Access Switch",
            "slug": "access-switch",
        },
        "tenant": {
            "id": 1,
            "url": "https://netboxdemo.com/api/tenancy/tenants/1/",
            "display": "Starfleet",
            "name": "Starfleet",
            "slug": "starfleet",
        },
        "platform": None,
        "serial": "FOC123452",
        "asset_tag": None,
        "site": {
            "id": 1,
            "url": "https://netboxdemo.com/api/dcim/sites/1/",
            "display": "NCC-1701-D",
            "name": "NCC-1701-D",
            "slug": "ncc-1701-d",
        },
        "location": {
            "id": 1,
            "url": "https://netboxdemo.com/api/dcim/locations/1/",
            "display": "MDF Room",
            "name": "MDF Room",
            "slug": "mdf-room",
            "_depth": 0,
        },
        "rack": {
            "id": 1,
            "url": "https://netboxdemo.com/api/dcim/racks/1/",
            "display": "MDF_RACK1",
            "name": "MDF_RACK1",
            "display_name": "MDF_RACK1",
        },
        "position": 24,
        "face": {"value": "front", "label": "Front"},
        "parent_device": None,
        "status": {"value": "active", "label": "Active"},
        "primary_ip": None,
        "primary_ip4": None,
        "primary_ip6": None,
        "cluster": None,
        "virtual_chassis": {
            "id": 1,
            "name": "1701_MDF_ACCESS-sw1",
            "url": "https://netboxdemo.com/api/dcim/virtual-chassis/1/",
            "master": {
                "id": 2,
                "url": "https://netboxdemo.com/api/dcim/devices/2/",
                "display": "1701_MDF_ACCESS-sw1",
                "name": "1701_MDF_ACCESS-sw1",
                "display_name": "1701_MDF_ACCESS-sw1",
            },
        },
        "vc_position": 2,
        "vc_priority": 14,
        "comments": "",
        "local_context_data": None,
        "tags": [],
        "custom_fields": {},
        "config_context": {},
        "created": "2019-12-22",
        "last_updated": "2019-12-22T17:16:35.024601Z",
    },
    {
        "id": 11,
        "url": "https://netboxdemo.com/api/dcim/devices/11/",
        "display": "1701_MDF_R1_PDU_A",
        "name": "1701_MDF_R1_PDU_A",
        "display_name": "1701_MDF_R1_PDU_A",
        "device_type": {
            "id": 5,
            "url": "https://netboxdemo.com/api/dcim/device-types/5/",
            "display": "PDU1230",
            "manufacturer": {
                "id": 4,
                "url": "https://netboxdemo.com/api/dcim/manufacturers/4/",
                "display": "Tripp Lite",
                "name": "Tripp Lite",
                "slug": "tripp-lite",
            },
            "model": "PDU1230",
            "slug": "pdu1230",
            "display_name": "Tripp Lite PDU1230",
        },
        "device_role": {
            "id": 6,
            "url": "https://netboxdemo.com/api/dcim/device-roles/6/",
            "display": "PDU",
            "name": "PDU",
            "slug": "pdu",
        },
        "tenant": {
            "id": 1,
            "url": "https://netboxdemo.com/api/tenancy/tenants/1/",
            "display": "Starfleet",
            "name": "Starfleet",
            "slug": "starfleet",
        },
        "platform": None,
        "serial": "",
        "asset_tag": None,
        "site": {
            "id": 1,
            "url": "https://netboxdemo.com/api/dcim/sites/1/",
            "display": "NCC-1701-D",
            "name": "NCC-1701-D",
            "slug": "ncc-1701-d",
        },
        "location": {
            "id": 1,
            "url": "https://netboxdemo.com/api/dcim/locations/1/",
            "display": "MDF Room",
            "name": "MDF Room",
            "slug": "mdf-room",
            "_depth": 0,
        },
        "rack": {
            "id": 1,
            "url": "https://netboxdemo.com/api/dcim/racks/1/",
            "display": "MDF_RACK1",
            "name": "MDF_RACK1",
            "display_name": "MDF_RACK1",
        },
        "position": 2,
        "face": {"value": "front", "label": "Front"},
        "parent_device": None,
        "status": {"value": "active", "label": "Active"},
        "primary_ip": None,
        "primary_ip4": None,
        "primary_ip6": None,
        "cluster": None,
        "virtual_chassis": None,
        "vc_position": None,
        "vc_priority": None,
        "comments": "",
        "local_context_data": None,
        "tags": [],
        "custom_fields": {},
        "config_context": {},
        "created": "2019-12-22",
        "last_updated": "2019-12-22T18:01:04.149862Z",
    },
    {
        "id": 12,
        "url": "https://netboxdemo.com/api/dcim/devices/12/",
        "display": "1701_MDF_R1_PDU_B",
        "name": "1701_MDF_R1_PDU_B",
        "display_name": "1701_MDF_R1_PDU_B",
        "device_type": {
            "id": 5,
            "url": "https://netboxdemo.com/api/dcim/device-types/5/",
            "display": "PDU1230",
            "manufacturer": {
                "id": 4,
                "url": "https://netboxdemo.com/api/dcim/manufacturers/4/",
                "display": "Tripp Lite",
                "name": "Tripp Lite",
                "slug": "tripp-lite",
            },
            "model": "PDU1230",
            "slug": "pdu1230",
            "display_name": "Tripp Lite PDU1230",
        },
        "device_role": {
            "id": 6,
            "url": "https://netboxdemo.com/api/dcim/device-roles/6/",
            "display": "PDU",
            "name": "PDU",
            "slug": "pdu",
        },
        "tenant": {
            "id": 1,
            "url": "https://netboxdemo.com/api/tenancy/tenants/1/",
            "display": "Starfleet",
            "name": "Starfleet",
            "slug": "starfleet",
        },
        "platform": None,
        "serial": "",
        "asset_tag": None,
        "site": {
            "id": 1,
            "url": "https://netboxdemo.com/api/dcim/sites/1/",
            "display": "NCC-1701-D",
            "name": "NCC-1701-D",
            "slug": "ncc-1701-d",
        },
        "location": {
            "id": 1,
            "url": "https://netboxdemo.com/api/dcim/locations/1/",
            "display": "MDF Room",
            "name": "MDF Room",
            "slug": "mdf-room",
            "_depth": 0,
        },
        "rack": {
            "id": 1,
            "url": "https://netboxdemo.com/api/dcim/racks/1/",
            "display": "MDF_RACK1",
            "name": "MDF_RACK1",
            "display_name": "MDF_RACK1",
        },
        "position": 1,
        "face": {"value": "front", "label": "Front"},
        "parent_device": None,
        "status": {"value": "active", "label": "Active"},
        "primary_ip": None,
        "primary_ip4": None,
        "primary_ip6": None,
        "cluster": None,
        "virtual_chassis": None,
        "vc_position": None,
        "vc_priority": None,
        "comments": "",
        "local_context_data": None,
        "tags": [],
        "custom_fields": {},
        "config_context": {},
        "created": "2019-12-22",
        "last_updated": "2019-12-22T18:01:24.761049Z",
    },
    {
        "id": 8,
        "url": "https://netboxdemo.com/api/dcim/devices/8/",
        "display": "1701_MDF_R1_U40",
        "name": "1701_MDF_R1_U40",
        "display_name": "1701_MDF_R1_U40",
        "device_type": {
            "id": 2,
            "url": "https://netboxdemo.com/api/dcim/device-types/2/",
            "display": "CPPA-UDDM-SL-1U-24",
            "manufacturer": {
                "id": 3,
                "url": "https://netboxdemo.com/api/dcim/manufacturers/3/",
                "display": "Commscope",
                "name": "Commscope",
                "slug": "commscope",
            },
            "model": "CPPA-UDDM-SL-1U-24",
            "slug": "cppa-uddm-sl-1u-24",
            "display_name": "Commscope CPPA-UDDM-SL-1U-24",
        },
        "device_role": {
            "id": 4,
            "url": "https://netboxdemo.com/api/dcim/device-roles/4/",
            "display": "Copper Patch Panel",
            "name": "Copper Patch Panel",
            "slug": "copper-patch-panel",
        },
        "tenant": {
            "id": 1,
            "url": "https://netboxdemo.com/api/tenancy/tenants/1/",
            "display": "Starfleet",
            "name": "Starfleet",
            "slug": "starfleet",
        },
        "platform": None,
        "serial": "",
        "asset_tag": None,
        "site": {
            "id": 1,
            "url": "https://netboxdemo.com/api/dcim/sites/1/",
            "display": "NCC-1701-D",
            "name": "NCC-1701-D",
            "slug": "ncc-1701-d",
        },
        "location": {
            "id": 1,
            "url": "https://netboxdemo.com/api/dcim/locations/1/",
            "display": "MDF Room",
            "name": "MDF Room",
            "slug": "mdf-room",
            "_depth": 0,
        },
        "rack": {
            "id": 1,
            "url": "https://netboxdemo.com/api/dcim/racks/1/",
            "display": "MDF_RACK1",
            "name": "MDF_RACK1",
            "display_name": "MDF_RACK1",
        },
        "position": 40,
        "face": {"value": "front", "label": "Front"},
        "parent_device": None,
        "status": {"value": "active", "label": "Active"},
        "primary_ip": None,
        "primary_ip4": None,
        "primary_ip6": None,
        "cluster": None,
        "virtual_chassis": None,
        "vc_position": None,
        "vc_priority": None,
        "comments": "",
        "local_context_data": None,
        "tags": [],
        "custom_fields": {},
        "config_context": {},
        "created": "2019-12-22",
        "last_updated": "2019-12-22T17:33:21.461572Z",
    },
    {
        "id": 7,
        "url": "https://netboxdemo.com/api/dcim/devices/7/",
        "display": "1701_MDF_R1_U41",
        "name": "1701_MDF_R1_U41",
        "display_name": "1701_MDF_R1_U41",
        "device_type": {
            "id": 2,
            "url": "https://netboxdemo.com/api/dcim/device-types/2/",
            "display": "CPPA-UDDM-SL-1U-24",
            "manufacturer": {
                "id": 3,
                "url": "https://netboxdemo.com/api/dcim/manufacturers/3/",
                "display": "Commscope",
                "name": "Commscope",
                "slug": "commscope",
            },
            "model": "CPPA-UDDM-SL-1U-24",
            "slug": "cppa-uddm-sl-1u-24",
            "display_name": "Commscope CPPA-UDDM-SL-1U-24",
        },
        "device_role": {
            "id": 4,
            "url": "https://netboxdemo.com/api/dcim/device-roles/4/",
            "display": "Copper Patch Panel",
            "name": "Copper Patch Panel",
            "slug": "copper-patch-panel",
        },
        "tenant": {
            "id": 1,
            "url": "https://netboxdemo.com/api/tenancy/tenants/1/",
            "display": "Starfleet",
            "name": "Starfleet",
            "slug": "starfleet",
        },
        "platform": None,
        "serial": "",
        "asset_tag": None,
        "site": {
            "id": 1,
            "url": "https://netboxdemo.com/api/dcim/sites/1/",
            "display": "NCC-1701-D",
            "name": "NCC-1701-D",
            "slug": "ncc-1701-d",
        },
        "location": {
            "id": 1,
            "url": "https://netboxdemo.com/api/dcim/locations/1/",
            "display": "MDF Room",
            "name": "MDF Room",
            "slug": "mdf-room",
            "_depth": 0,
        },
        "rack": {
            "id": 1,
            "url": "https://netboxdemo.com/api/dcim/racks/1/",
            "display": "MDF_RACK1",
            "name": "MDF_RACK1",
            "display_name": "MDF_RACK1",
        },
        "position": 41,
        "face": {"value": "front", "label": "Front"},
        "parent_device": None,
        "status": {"value": "active", "label": "Active"},
        "primary_ip": None,
        "primary_ip4": None,
        "primary_ip6": None,
        "cluster": None,
        "virtual_chassis": None,
        "vc_position": None,
        "vc_priority": None,
        "comments": "",
        "local_context_data": None,
        "tags": [],
        "custom_fields": {},
        "config_context": {},
        "created": "2019-12-22",
        "last_updated": "2019-12-22T17:32:47.122010Z",
    },
    {
        "id": 4,
        "url": "https://netboxdemo.com/api/dcim/devices/4/",
        "display": "1701_MDF_R1_U42",
        "name": "1701_MDF_R1_U42",
        "display_name": "1701_MDF_R1_U42",
        "device_type": {
            "id": 1,
            "url": "https://netboxdemo.com/api/dcim/device-types/1/",
            "display": "760231449 | SD-1U",
            "manufacturer": {
                "id": 3,
                "url": "https://netboxdemo.com/api/dcim/manufacturers/3/",
                "display": "Commscope",
                "name": "Commscope",
                "slug": "commscope",
            },
            "model": "760231449 | SD-1U",
            "slug": "760231449-sd-1u",
            "display_name": "Commscope 760231449 | SD-1U",
        },
        "device_role": {
            "id": 5,
            "url": "https://netboxdemo.com/api/dcim/device-roles/5/",
            "display": "Fiber Patch Panel",
            "name": "Fiber Patch Panel",
            "slug": "fiber-patch-panel",
        },
        "tenant": {
            "id": 1,
            "url": "https://netboxdemo.com/api/tenancy/tenants/1/",
            "display": "Starfleet",
            "name": "Starfleet",
            "slug": "starfleet",
        },
        "platform": None,
        "serial": "",
        "asset_tag": None,
        "site": {
            "id": 1,
            "url": "https://netboxdemo.com/api/dcim/sites/1/",
            "display": "NCC-1701-D",
            "name": "NCC-1701-D",
            "slug": "ncc-1701-d",
        },
        "location": {
            "id": 1,
            "url": "https://netboxdemo.com/api/dcim/locations/1/",
            "display": "MDF Room",
            "name": "MDF Room",
            "slug": "mdf-room",
            "_depth": 0,
        },
        "rack": {
            "id": 1,
            "url": "https://netboxdemo.com/api/dcim/racks/1/",
            "display": "MDF_RACK1",
            "name": "MDF_RACK1",
            "display_name": "MDF_RACK1",
        },
        "position": 42,
        "face": {"value": "front", "label": "Front"},
        "parent_device": None,
        "status": {"value": "active", "label": "Active"},
        "primary_ip": None,
        "primary_ip4": None,
        "primary_ip6": None,
        "cluster": None,
        "virtual_chassis": None,
        "vc_position": None,
        "vc_priority": None,
        "comments": "",
        "local_context_data": None,
        "tags": [],
        "custom_fields": {},
        "config_context": {},
        "created": "2019-12-22",
        "last_updated": "2019-12-22T17:31:22.445585Z",
    },
    {
        "id": 6,
        "url": "https://netboxdemo.com/api/dcim/devices/6/",
        "display": "1701_RR_ACCESS",
        "name": "1701_RR_ACCESS",
        "display_name": "1701_RR_ACCESS",
        "device_type": {
            "id": 4,
            "url": "https://netboxdemo.com/api/dcim/device-types/4/",
            "display": "WS-C3850-48U",
            "manufacturer": {
                "id": 2,
                "url": "https://netboxdemo.com/api/dcim/manufacturers/2/",
                "display": "Cisco",
                "name": "Cisco",
                "slug": "cisco",
            },
            "model": "WS-C3850-48U",
            "slug": "ws-c3850-48u",
            "display_name": "Cisco WS-C3850-48U",
        },
        "device_role": {
            "id": 2,
            "url": "https://netboxdemo.com/api/dcim/device-roles/2/",
            "display": "Access Switch",
            "name": "Access Switch",
            "slug": "access-switch",
        },
        "tenant": {
            "id": 1,
            "url": "https://netboxdemo.com/api/tenancy/tenants/1/",
            "display": "Starfleet",
            "name": "Starfleet",
            "slug": "starfleet",
        },
        "platform": None,
        "serial": "FCW54543123",
        "asset_tag": None,
        "site": {
            "id": 1,
            "url": "https://netboxdemo.com/api/dcim/sites/1/",
            "display": "NCC-1701-D",
            "name": "NCC-1701-D",
            "slug": "ncc-1701-d",
        },
        "location": None,
        "rack": {
            "id": 5,
            "url": "https://netboxdemo.com/api/dcim/racks/5/",
            "display": "READY_ROOM_IDF",
            "name": "READY_ROOM_IDF",
            "display_name": "READY_ROOM_IDF",
        },
        "position": 5,
        "face": {"value": "front", "label": "Front"},
        "parent_device": None,
        "status": {"value": "active", "label": "Active"},
        "primary_ip": None,
        "primary_ip4": None,
        "primary_ip6": None,
        "cluster": None,
        "virtual_chassis": None,
        "vc_position": None,
        "vc_priority": None,
        "comments": "",
        "local_context_data": None,
        "tags": [],
        "custom_fields": {},
        "config_context": {},
        "created": "2019-12-22",
        "last_updated": "2019-12-22T20:00:10.479576Z",
    },
    {
        "id": 10,
        "url": "https://netboxdemo.com/api/dcim/devices/10/",
        "display": "1701_RR_IDF_PDU",
        "name": "1701_RR_IDF_PDU",
        "display_name": "1701_RR_IDF_PDU",
        "device_type": {
            "id": 5,
            "url": "https://netboxdemo.com/api/dcim/device-types/5/",
            "display": "PDU1230",
            "manufacturer": {
                "id": 4,
                "url": "https://netboxdemo.com/api/dcim/manufacturers/4/",
                "display": "Tripp Lite",
                "name": "Tripp Lite",
                "slug": "tripp-lite",
            },
            "model": "PDU1230",
            "slug": "pdu1230",
            "display_name": "Tripp Lite PDU1230",
        },
        "device_role": {
            "id": 6,
            "url": "https://netboxdemo.com/api/dcim/device-roles/6/",
            "display": "PDU",
            "name": "PDU",
            "slug": "pdu",
        },
        "tenant": {
            "id": 1,
            "url": "https://netboxdemo.com/api/tenancy/tenants/1/",
            "display": "Starfleet",
            "name": "Starfleet",
            "slug": "starfleet",
        },
        "platform": None,
        "serial": "",
        "asset_tag": None,
        "site": {
            "id": 1,
            "url": "https://netboxdemo.com/api/dcim/sites/1/",
            "display": "NCC-1701-D",
            "name": "NCC-1701-D",
            "slug": "ncc-1701-d",
        },
        "location": None,
        "rack": {
            "id": 5,
            "url": "https://netboxdemo.com/api/dcim/racks/5/",
            "display": "READY_ROOM_IDF",
            "name": "READY_ROOM_IDF",
            "display_name": "READY_ROOM_IDF",
        },
        "position": 1,
        "face": {"value": "front", "label": "Front"},
        "parent_device": None,
        "status": {"value": "active", "label": "Active"},
        "primary_ip": None,
        "primary_ip4": None,
        "primary_ip6": None,
        "cluster": None,
        "virtual_chassis": None,
        "vc_position": None,
        "vc_priority": None,
        "comments": "",
        "local_context_data": None,
        "tags": [],
        "custom_fields": {},
        "config_context": {},
        "created": "2019-12-22",
        "last_updated": "2019-12-22T17:58:08.802625Z",
    },
    {
        "id": 9,
        "url": "https://netboxdemo.com/api/dcim/devices/9/",
        "display": "1701_RR_IDF_U7",
        "name": "1701_RR_IDF_U7",
        "display_name": "1701_RR_IDF_U7",
        "device_type": {
            "id": 2,
            "url": "https://netboxdemo.com/api/dcim/device-types/2/",
            "display": "CPPA-UDDM-SL-1U-24",
            "manufacturer": {
                "id": 3,
                "url": "https://netboxdemo.com/api/dcim/manufacturers/3/",
                "display": "Commscope",
                "name": "Commscope",
                "slug": "commscope",
            },
            "model": "CPPA-UDDM-SL-1U-24",
            "slug": "cppa-uddm-sl-1u-24",
            "display_name": "Commscope CPPA-UDDM-SL-1U-24",
        },
        "device_role": {
            "id": 4,
            "url": "https://netboxdemo.com/api/dcim/device-roles/4/",
            "display": "Copper Patch Panel",
            "name": "Copper Patch Panel",
            "slug": "copper-patch-panel",
        },
        "tenant": {
            "id": 1,
            "url": "https://netboxdemo.com/api/tenancy/tenants/1/",
            "display": "Starfleet",
            "name": "Starfleet",
            "slug": "starfleet",
        },
        "platform": None,
        "serial": "",
        "asset_tag": None,
        "site": {
            "id": 1,
            "url": "https://netboxdemo.com/api/dcim/sites/1/",
            "display": "NCC-1701-D",
            "name": "NCC-1701-D",
            "slug": "ncc-1701-d",
        },
        "location": None,
        "rack": {
            "id": 5,
            "url": "https://netboxdemo.com/api/dcim/racks/5/",
            "display": "READY_ROOM_IDF",
            "name": "READY_ROOM_IDF",
            "display_name": "READY_ROOM_IDF",
        },
        "position": 7,
        "face": {"value": "front", "label": "Front"},
        "parent_device": None,
        "status": {"value": "active", "label": "Active"},
        "primary_ip": None,
        "primary_ip4": None,
        "primary_ip6": None,
        "cluster": None,
        "virtual_chassis": None,
        "vc_position": None,
        "vc_priority": None,
        "comments": "",
        "local_context_data": None,
        "tags": [],
        "custom_fields": {},
        "config_context": {},
        "created": "2019-12-22",
        "last_updated": "2019-12-22T17:36:09.656628Z",
    },
    {
        "id": 5,
        "url": "https://netboxdemo.com/api/dcim/devices/5/",
        "display": "1701_RR_IDF_U8",
        "name": "1701_RR_IDF_U8",
        "display_name": "1701_RR_IDF_U8",
        "device_type": {
            "id": 1,
            "url": "https://netboxdemo.com/api/dcim/device-types/1/",
            "display": "760231449 | SD-1U",
            "manufacturer": {
                "id": 3,
                "url": "https://netboxdemo.com/api/dcim/manufacturers/3/",
                "display": "Commscope",
                "name": "Commscope",
                "slug": "commscope",
            },
            "model": "760231449 | SD-1U",
            "slug": "760231449-sd-1u",
            "display_name": "Commscope 760231449 | SD-1U",
        },
        "device_role": {
            "id": 5,
            "url": "https://netboxdemo.com/api/dcim/device-roles/5/",
            "display": "Fiber Patch Panel",
            "name": "Fiber Patch Panel",
            "slug": "fiber-patch-panel",
        },
        "tenant": {
            "id": 1,
            "url": "https://netboxdemo.com/api/tenancy/tenants/1/",
            "display": "Starfleet",
            "name": "Starfleet",
            "slug": "starfleet",
        },
        "platform": None,
        "serial": "",
        "asset_tag": None,
        "site": {
            "id": 1,
            "url": "https://netboxdemo.com/api/dcim/sites/1/",
            "display": "NCC-1701-D",
            "name": "NCC-1701-D",
            "slug": "ncc-1701-d",
        },
        "location": None,
        "rack": {
            "id": 5,
            "url": "https://netboxdemo.com/api/dcim/racks/5/",
            "display": "READY_ROOM_IDF",
            "name": "READY_ROOM_IDF",
            "display_name": "READY_ROOM_IDF",
        },
        "position": 8,
        "face": {"value": "front", "label": "Front"},
        "parent_device": None,
        "status": {"value": "active", "label": "Active"},
        "primary_ip": None,
        "primary_ip4": None,
        "primary_ip6": None,
        "cluster": None,
        "virtual_chassis": None,
        "vc_position": None,
        "vc_priority": None,
        "comments": "",
        "local_context_data": None,
        "tags": [],
        "custom_fields": {},
        "config_context": {},
        "created": "2019-12-22",
        "last_updated": "2019-12-22T17:31:30.410258Z",
    },
    {
        "id": 24,
        "url": "https://netboxdemo.com/api/dcim/devices/24/",
        "display": "DS9_CORE_ACCESS",
        "name": "DS9_CORE_ACCESS",
        "display_name": "DS9_CORE_ACCESS",
        "device_type": {
            "id": 4,
            "url": "https://netboxdemo.com/api/dcim/device-types/4/",
            "display": "WS-C3850-48U",
            "manufacturer": {
                "id": 2,
                "url": "https://netboxdemo.com/api/dcim/manufacturers/2/",
                "display": "Cisco",
                "name": "Cisco",
                "slug": "cisco",
            },
            "model": "WS-C3850-48U",
            "slug": "ws-c3850-48u",
            "display_name": "Cisco WS-C3850-48U",
        },
        "device_role": {
            "id": 2,
            "url": "https://netboxdemo.com/api/dcim/device-roles/2/",
            "display": "Access Switch",
            "name": "Access Switch",
            "slug": "access-switch",
        },
        "tenant": {
            "id": 2,
            "url": "https://netboxdemo.com/api/tenancy/tenants/2/",
            "display": "Bajor",
            "name": "Bajor",
            "slug": "bajor",
        },
        "platform": {
            "id": 2,
            "url": "https://netboxdemo.com/api/dcim/platforms/2/",
            "display": "Cisco IOS-XE",
            "name": "Cisco IOS-XE",
            "slug": "cisco-ios-xe",
        },
        "serial": "",
        "asset_tag": None,
        "site": {
            "id": 2,
            "url": "https://netboxdemo.com/api/dcim/sites/2/",
            "display": "DS9",
            "name": "DS9",
            "slug": "ds9",
        },
        "location": None,
        "rack": {
            "id": 4,
            "url": "https://netboxdemo.com/api/dcim/racks/4/",
            "display": "CORE_RACK",
            "name": "CORE_RACK",
            "display_name": "CORE_RACK",
        },
        "position": 28,
        "face": {"value": "front", "label": "Front"},
        "parent_device": None,
        "status": {"value": "active", "label": "Active"},
        "primary_ip": None,
        "primary_ip4": None,
        "primary_ip6": None,
        "cluster": None,
        "virtual_chassis": None,
        "vc_position": None,
        "vc_priority": None,
        "comments": "",
        "local_context_data": None,
        "tags": [],
        "custom_fields": {},
        "config_context": {},
        "created": "2019-12-22",
        "last_updated": "2019-12-22T18:33:10.836533Z",
    },
    {
        "id": 15,
        "url": "https://netboxdemo.com/api/dcim/devices/15/",
        "display": "DS9_CORE_FIBER_U42",
        "name": "DS9_CORE_FIBER_U42",
        "display_name": "DS9_CORE_FIBER_U42",
        "device_type": {
            "id": 1,
            "url": "https://netboxdemo.com/api/dcim/device-types/1/",
            "display": "760231449 | SD-1U",
            "manufacturer": {
                "id": 3,
                "url": "https://netboxdemo.com/api/dcim/manufacturers/3/",
                "display": "Commscope",
                "name": "Commscope",
                "slug": "commscope",
            },
            "model": "760231449 | SD-1U",
            "slug": "760231449-sd-1u",
            "display_name": "Commscope 760231449 | SD-1U",
        },
        "device_role": {
            "id": 5,
            "url": "https://netboxdemo.com/api/dcim/device-roles/5/",
            "display": "Fiber Patch Panel",
            "name": "Fiber Patch Panel",
            "slug": "fiber-patch-panel",
        },
        "tenant": {
            "id": 2,
            "url": "https://netboxdemo.com/api/tenancy/tenants/2/",
            "display": "Bajor",
            "name": "Bajor",
            "slug": "bajor",
        },
        "platform": None,
        "serial": "",
        "asset_tag": None,
        "site": {
            "id": 2,
            "url": "https://netboxdemo.com/api/dcim/sites/2/",
            "display": "DS9",
            "name": "DS9",
            "slug": "ds9",
        },
        "location": None,
        "rack": {
            "id": 4,
            "url": "https://netboxdemo.com/api/dcim/racks/4/",
            "display": "CORE_RACK",
            "name": "CORE_RACK",
            "display_name": "CORE_RACK",
        },
        "position": 42,
        "face": {"value": "front", "label": "Front"},
        "parent_device": None,
        "status": {"value": "active", "label": "Active"},
        "primary_ip": None,
        "primary_ip4": None,
        "primary_ip6": None,
        "cluster": None,
        "virtual_chassis": None,
        "vc_position": None,
        "vc_priority": None,
        "comments": "",
        "local_context_data": None,
        "tags": [],
        "custom_fields": {},
        "config_context": {},
        "created": "2019-12-22",
        "last_updated": "2019-12-22T18:23:16.984678Z",
    },
    {
        "id": 13,
        "url": "https://netboxdemo.com/api/dcim/devices/13/",
        "display": "DS9_CORE_PDU_A",
        "name": "DS9_CORE_PDU_A",
        "display_name": "DS9_CORE_PDU_A",
        "device_type": {
            "id": 5,
            "url": "https://netboxdemo.com/api/dcim/device-types/5/",
            "display": "PDU1230",
            "manufacturer": {
                "id": 4,
                "url": "https://netboxdemo.com/api/dcim/manufacturers/4/",
                "display": "Tripp Lite",
                "name": "Tripp Lite",
                "slug": "tripp-lite",
            },
            "model": "PDU1230",
            "slug": "pdu1230",
            "display_name": "Tripp Lite PDU1230",
        },
        "device_role": {
            "id": 6,
            "url": "https://netboxdemo.com/api/dcim/device-roles/6/",
            "display": "PDU",
            "name": "PDU",
            "slug": "pdu",
        },
        "tenant": {
            "id": 2,
            "url": "https://netboxdemo.com/api/tenancy/tenants/2/",
            "display": "Bajor",
            "name": "Bajor",
            "slug": "bajor",
        },
        "platform": None,
        "serial": "",
        "asset_tag": None,
        "site": {
            "id": 2,
            "url": "https://netboxdemo.com/api/dcim/sites/2/",
            "display": "DS9",
            "name": "DS9",
            "slug": "ds9",
        },
        "location": None,
        "rack": {
            "id": 4,
            "url": "https://netboxdemo.com/api/dcim/racks/4/",
            "display": "CORE_RACK",
            "name": "CORE_RACK",
            "display_name": "CORE_RACK",
        },
        "position": 2,
        "face": {"value": "front", "label": "Front"},
        "parent_device": None,
        "status": {"value": "active", "label": "Active"},
        "primary_ip": None,
        "primary_ip4": None,
        "primary_ip6": None,
        "cluster": None,
        "virtual_chassis": None,
        "vc_position": None,
        "vc_priority": None,
        "comments": "",
        "local_context_data": None,
        "tags": [],
        "custom_fields": {},
        "config_context": {},
        "created": "2019-12-22",
        "last_updated": "2019-12-22T18:19:40.554239Z",
    },
    {
        "id": 14,
        "url": "https://netboxdemo.com/api/dcim/devices/14/",
        "display": "DS9_CORE_PDU_B",
        "name": "DS9_CORE_PDU_B",
        "display_name": "DS9_CORE_PDU_B",
        "device_type": {
            "id": 5,
            "url": "https://netboxdemo.com/api/dcim/device-types/5/",
            "display": "PDU1230",
            "manufacturer": {
                "id": 4,
                "url": "https://netboxdemo.com/api/dcim/manufacturers/4/",
                "display": "Tripp Lite",
                "name": "Tripp Lite",
                "slug": "tripp-lite",
            },
            "model": "PDU1230",
            "slug": "pdu1230",
            "display_name": "Tripp Lite PDU1230",
        },
        "device_role": {
            "id": 6,
            "url": "https://netboxdemo.com/api/dcim/device-roles/6/",
            "display": "PDU",
            "name": "PDU",
            "slug": "pdu",
        },
        "tenant": {
            "id": 2,
            "url": "https://netboxdemo.com/api/tenancy/tenants/2/",
            "display": "Bajor",
            "name": "Bajor",
            "slug": "bajor",
        },
        "platform": None,
        "serial": "",
        "asset_tag": None,
        "site": {
            "id": 2,
            "url": "https://netboxdemo.com/api/dcim/sites/2/",
            "display": "DS9",
            "name": "DS9",
            "slug": "ds9",
        },
        "location": None,
        "rack": {
            "id": 4,
            "url": "https://netboxdemo.com/api/dcim/racks/4/",
            "display": "CORE_RACK",
            "name": "CORE_RACK",
            "display_name": "CORE_RACK",
        },
        "position": 1,
        "face": {"value": "front", "label": "Front"},
        "parent_device": None,
        "status": {"value": "active", "label": "Active"},
        "primary_ip": None,
        "primary_ip4": None,
        "primary_ip6": None,
        "cluster": None,
        "virtual_chassis": None,
        "vc_position": None,
        "vc_priority": None,
        "comments": "",
        "local_context_data": None,
        "tags": [],
        "custom_fields": {},
        "config_context": {},
        "created": "2019-12-22",
        "last_updated": "2019-12-22T18:20:18.897526Z",
    },
    {
        "id": 23,
        "url": "https://netboxdemo.com/api/dcim/devices/23/",
        "display": "DS9_CORE_SWITCH",
        "name": "DS9_CORE_SWITCH",
        "display_name": "DS9_CORE_SWITCH",
        "device_type": {
            "id": 3,
            "url": "https://netboxdemo.com/api/dcim/device-types/3/",
            "display": "S4028-ON",
            "manufacturer": {
                "id": 1,
                "url": "https://netboxdemo.com/api/dcim/manufacturers/1/",
                "display": "Dell",
                "name": "Dell",
                "slug": "dell",
            },
            "model": "S4028-ON",
            "slug": "s4028-on",
            "display_name": "Dell S4028-ON",
        },
        "device_role": {
            "id": 1,
            "url": "https://netboxdemo.com/api/dcim/device-roles/1/",
            "display": "Core Switch",
            "name": "Core Switch",
            "slug": "core-switch",
        },
        "tenant": {
            "id": 2,
            "url": "https://netboxdemo.com/api/tenancy/tenants/2/",
            "display": "Bajor",
            "name": "Bajor",
            "slug": "bajor",
        },
        "platform": None,
        "serial": "64341232574621",
        "asset_tag": None,
        "site": {
            "id": 2,
            "url": "https://netboxdemo.com/api/dcim/sites/2/",
            "display": "DS9",
            "name": "DS9",
            "slug": "ds9",
        },
        "location": None,
        "rack": {
            "id": 4,
            "url": "https://netboxdemo.com/api/dcim/racks/4/",
            "display": "CORE_RACK",
            "name": "CORE_RACK",
            "display_name": "CORE_RACK",
        },
        "position": 33,
        "face": {"value": "front", "label": "Front"},
        "parent_device": None,
        "status": {"value": "active", "label": "Active"},
        "primary_ip": {
            "id": 13,
            "url": "https://netboxdemo.com/api/ipam/ip-addresses/13/",
            "display": "2001:db8:d59::2/64",
            "family": 6,
            "address": "2001:db8:d59::2/64",
        },
        "primary_ip4": {
            "id": 15,
            "url": "https://netboxdemo.com/api/ipam/ip-addresses/15/",
            "display": "10.10.0.2/24",
            "family": 4,
            "address": "10.10.0.2/24",
        },
        "primary_ip6": {
            "id": 13,
            "url": "https://netboxdemo.com/api/ipam/ip-addresses/13/",
            "display": "2001:db8:d59::2/64",
            "family": 6,
            "address": "2001:db8:d59::2/64",
        },
        "cluster": None,
        "virtual_chassis": None,
        "vc_position": None,
        "vc_priority": None,
        "comments": "",
        "local_context_data": None,
        "tags": [],
        "custom_fields": {},
        "config_context": {},
        "created": "2019-12-22",
        "last_updated": "2019-12-22T20:08:47.543020Z",
    },
    {
        "id": 22,
        "url": "https://netboxdemo.com/api/dcim/devices/22/",
        "display": "DS9_CORE_U41",
        "name": "DS9_CORE_U41",
        "display_name": "DS9_CORE_U41",
        "device_type": {
            "id": 2,
            "url": "https://netboxdemo.com/api/dcim/device-types/2/",
            "display": "CPPA-UDDM-SL-1U-24",
            "manufacturer": {
                "id": 3,
                "url": "https://netboxdemo.com/api/dcim/manufacturers/3/",
                "display": "Commscope",
                "name": "Commscope",
                "slug": "commscope",
            },
            "model": "CPPA-UDDM-SL-1U-24",
            "slug": "cppa-uddm-sl-1u-24",
            "display_name": "Commscope CPPA-UDDM-SL-1U-24",
        },
        "device_role": {
            "id": 4,
            "url": "https://netboxdemo.com/api/dcim/device-roles/4/",
            "display": "Copper Patch Panel",
            "name": "Copper Patch Panel",
            "slug": "copper-patch-panel",
        },
        "tenant": {
            "id": 2,
            "url": "https://netboxdemo.com/api/tenancy/tenants/2/",
            "display": "Bajor",
            "name": "Bajor",
            "slug": "bajor",
        },
        "platform": None,
        "serial": "",
        "asset_tag": None,
        "site": {
            "id": 2,
            "url": "https://netboxdemo.com/api/dcim/sites/2/",
            "display": "DS9",
            "name": "DS9",
            "slug": "ds9",
        },
        "location": None,
        "rack": {
            "id": 4,
            "url": "https://netboxdemo.com/api/dcim/racks/4/",
            "display": "CORE_RACK",
            "name": "CORE_RACK",
            "display_name": "CORE_RACK",
        },
        "position": 41,
        "face": {"value": "front", "label": "Front"},
        "parent_device": None,
        "status": {"value": "active", "label": "Active"},
        "primary_ip": None,
        "primary_ip4": None,
        "primary_ip6": None,
        "cluster": None,
        "virtual_chassis": None,
        "vc_position": None,
        "vc_priority": None,
        "comments": "",
        "local_context_data": None,
        "tags": [],
        "custom_fields": {},
        "config_context": {},
        "created": "2019-12-22",
        "last_updated": "2019-12-22T18:30:40.691185Z",
    },
    {
        "id": 28,
        "url": "https://netboxdemo.com/api/dcim/devices/28/",
        "display": "DS9_FW",
        "name": "DS9_FW",
        "display_name": "DS9_FW",
        "device_type": {
            "id": 6,
            "url": "https://netboxdemo.com/api/dcim/device-types/6/",
            "display": "PA-3020",
            "manufacturer": {
                "id": 5,
                "url": "https://netboxdemo.com/api/dcim/manufacturers/5/",
                "display": "Palo Alto",
                "name": "Palo Alto",
                "slug": "palo-alto",
            },
            "model": "PA-3020",
            "slug": "pa-3020",
            "display_name": "Palo Alto PA-3020",
        },
        "device_role": {
            "id": 3,
            "url": "https://netboxdemo.com/api/dcim/device-roles/3/",
            "display": "Firewall",
            "name": "Firewall",
            "slug": "firewall",
        },
        "tenant": {
            "id": 2,
            "url": "https://netboxdemo.com/api/tenancy/tenants/2/",
            "display": "Bajor",
            "name": "Bajor",
            "slug": "bajor",
        },
        "platform": None,
        "serial": "",
        "asset_tag": None,
        "site": {
            "id": 2,
            "url": "https://netboxdemo.com/api/dcim/sites/2/",
            "display": "DS9",
            "name": "DS9",
            "slug": "ds9",
        },
        "location": None,
        "rack": {
            "id": 4,
            "url": "https://netboxdemo.com/api/dcim/racks/4/",
            "display": "CORE_RACK",
            "name": "CORE_RACK",
            "display_name": "CORE_RACK",
        },
        "position": 37,
        "face": {"value": "front", "label": "Front"},
        "parent_device": None,
        "status": {"value": "active", "label": "Active"},
        "primary_ip": {
            "id": 11,
            "url": "https://netboxdemo.com/api/ipam/ip-addresses/11/",
            "display": "2001:db8:d59::1/64",
            "family": 6,
            "address": "2001:db8:d59::1/64",
        },
        "primary_ip4": {
            "id": 9,
            "url": "https://netboxdemo.com/api/ipam/ip-addresses/9/",
            "display": "10.10.0.1/24",
            "family": 4,
            "address": "10.10.0.1/24",
        },
        "primary_ip6": {
            "id": 11,
            "url": "https://netboxdemo.com/api/ipam/ip-addresses/11/",
            "display": "2001:db8:d59::1/64",
            "family": 6,
            "address": "2001:db8:d59::1/64",
        },
        "cluster": None,
        "virtual_chassis": None,
        "vc_position": None,
        "vc_priority": None,
        "comments": "",
        "local_context_data": None,
        "tags": [],
        "custom_fields": {},
        "config_context": {},
        "created": "2019-12-22",
        "last_updated": "2021-07-14T12:46:01.039284Z",
    },
    {
        "id": 25,
        "url": "https://netboxdemo.com/api/dcim/devices/25/",
        "display": "DS9_QUARKS_ACCESS",
        "name": "DS9_QUARKS_ACCESS",
        "display_name": "DS9_QUARKS_ACCESS",
        "device_type": {
            "id": 4,
            "url": "https://netboxdemo.com/api/dcim/device-types/4/",
            "display": "WS-C3850-48U",
            "manufacturer": {
                "id": 2,
                "url": "https://netboxdemo.com/api/dcim/manufacturers/2/",
                "display": "Cisco",
                "name": "Cisco",
                "slug": "cisco",
            },
            "model": "WS-C3850-48U",
            "slug": "ws-c3850-48u",
            "display_name": "Cisco WS-C3850-48U",
        },
        "device_role": {
            "id": 2,
            "url": "https://netboxdemo.com/api/dcim/device-roles/2/",
            "display": "Access Switch",
            "name": "Access Switch",
            "slug": "access-switch",
        },
        "tenant": {
            "id": 2,
            "url": "https://netboxdemo.com/api/tenancy/tenants/2/",
            "display": "Bajor",
            "name": "Bajor",
            "slug": "bajor",
        },
        "platform": {
            "id": 2,
            "url": "https://netboxdemo.com/api/dcim/platforms/2/",
            "display": "Cisco IOS-XE",
            "name": "Cisco IOS-XE",
            "slug": "cisco-ios-xe",
        },
        "serial": "",
        "asset_tag": None,
        "site": {
            "id": 2,
            "url": "https://netboxdemo.com/api/dcim/sites/2/",
            "display": "DS9",
            "name": "DS9",
            "slug": "ds9",
        },
        "location": {
            "id": 2,
            "url": "https://netboxdemo.com/api/dcim/locations/2/",
            "display": "DS9_IDFs",
            "name": "DS9_IDFs",
            "slug": "ds9_idfs",
            "_depth": 0,
        },
        "rack": {
            "id": 3,
            "url": "https://netboxdemo.com/api/dcim/racks/3/",
            "display": "QUARKS_UNDER_COUNTER",
            "name": "QUARKS_UNDER_COUNTER",
            "display_name": "QUARKS_UNDER_COUNTER",
        },
        "position": 4,
        "face": {"value": "front", "label": "Front"},
        "parent_device": None,
        "status": {"value": "active", "label": "Active"},
        "primary_ip": None,
        "primary_ip4": None,
        "primary_ip6": None,
        "cluster": None,
        "virtual_chassis": None,
        "vc_position": None,
        "vc_priority": None,
        "comments": "",
        "local_context_data": None,
        "tags": [],
        "custom_fields": {},
        "config_context": {},
        "created": "2019-12-22",
        "last_updated": "2019-12-22T18:43:56.640361Z",
    },
    {
        "id": 17,
        "url": "https://netboxdemo.com/api/dcim/devices/17/",
        "display": "DS9_QUARKS_FIBER_U8",
        "name": "DS9_QUARKS_FIBER_U8",
        "display_name": "DS9_QUARKS_FIBER_U8",
        "device_type": {
            "id": 1,
            "url": "https://netboxdemo.com/api/dcim/device-types/1/",
            "display": "760231449 | SD-1U",
            "manufacturer": {
                "id": 3,
                "url": "https://netboxdemo.com/api/dcim/manufacturers/3/",
                "display": "Commscope",
                "name": "Commscope",
                "slug": "commscope",
            },
            "model": "760231449 | SD-1U",
            "slug": "760231449-sd-1u",
            "display_name": "Commscope 760231449 | SD-1U",
        },
        "device_role": {
            "id": 5,
            "url": "https://netboxdemo.com/api/dcim/device-roles/5/",
            "display": "Fiber Patch Panel",
            "name": "Fiber Patch Panel",
            "slug": "fiber-patch-panel",
        },
        "tenant": {
            "id": 2,
            "url": "https://netboxdemo.com/api/tenancy/tenants/2/",
            "display": "Bajor",
            "name": "Bajor",
            "slug": "bajor",
        },
        "platform": None,
        "serial": "",
        "asset_tag": None,
        "site": {
            "id": 2,
            "url": "https://netboxdemo.com/api/dcim/sites/2/",
            "display": "DS9",
            "name": "DS9",
            "slug": "ds9",
        },
        "location": {
            "id": 2,
            "url": "https://netboxdemo.com/api/dcim/locations/2/",
            "display": "DS9_IDFs",
            "name": "DS9_IDFs",
            "slug": "ds9_idfs",
            "_depth": 0,
        },
        "rack": {
            "id": 3,
            "url": "https://netboxdemo.com/api/dcim/racks/3/",
            "display": "QUARKS_UNDER_COUNTER",
            "name": "QUARKS_UNDER_COUNTER",
            "display_name": "QUARKS_UNDER_COUNTER",
        },
        "position": 8,
        "face": {"value": "front", "label": "Front"},
        "parent_device": None,
        "status": {"value": "active", "label": "Active"},
        "primary_ip": None,
        "primary_ip4": None,
        "primary_ip6": None,
        "cluster": None,
        "virtual_chassis": None,
        "vc_position": None,
        "vc_priority": None,
        "comments": "",
        "local_context_data": None,
        "tags": [],
        "custom_fields": {},
        "config_context": {},
        "created": "2019-12-22",
        "last_updated": "2019-12-22T18:25:20.205659Z",
    },
    {
        "id": 19,
        "url": "https://netboxdemo.com/api/dcim/devices/19/",
        "display": "DS9_QUARKS_PDU",
        "name": "DS9_QUARKS_PDU",
        "display_name": "DS9_QUARKS_PDU",
        "device_type": {
            "id": 5,
            "url": "https://netboxdemo.com/api/dcim/device-types/5/",
            "display": "PDU1230",
            "manufacturer": {
                "id": 4,
                "url": "https://netboxdemo.com/api/dcim/manufacturers/4/",
                "display": "Tripp Lite",
                "name": "Tripp Lite",
                "slug": "tripp-lite",
            },
            "model": "PDU1230",
            "slug": "pdu1230",
            "display_name": "Tripp Lite PDU1230",
        },
        "device_role": {
            "id": 6,
            "url": "https://netboxdemo.com/api/dcim/device-roles/6/",
            "display": "PDU",
            "name": "PDU",
            "slug": "pdu",
        },
        "tenant": {
            "id": 2,
            "url": "https://netboxdemo.com/api/tenancy/tenants/2/",
            "display": "Bajor",
            "name": "Bajor",
            "slug": "bajor",
        },
        "platform": None,
        "serial": "",
        "asset_tag": None,
        "site": {
            "id": 2,
            "url": "https://netboxdemo.com/api/dcim/sites/2/",
            "display": "DS9",
            "name": "DS9",
            "slug": "ds9",
        },
        "location": {
            "id": 2,
            "url": "https://netboxdemo.com/api/dcim/locations/2/",
            "display": "DS9_IDFs",
            "name": "DS9_IDFs",
            "slug": "ds9_idfs",
            "_depth": 0,
        },
        "rack": {
            "id": 3,
            "url": "https://netboxdemo.com/api/dcim/racks/3/",
            "display": "QUARKS_UNDER_COUNTER",
            "name": "QUARKS_UNDER_COUNTER",
            "display_name": "QUARKS_UNDER_COUNTER",
        },
        "position": 1,
        "face": {"value": "front", "label": "Front"},
        "parent_device": None,
        "status": {"value": "active", "label": "Active"},
        "primary_ip": None,
        "primary_ip4": None,
        "primary_ip6": None,
        "cluster": None,
        "virtual_chassis": None,
        "vc_position": None,
        "vc_priority": None,
        "comments": "",
        "local_context_data": None,
        "tags": [],
        "custom_fields": {},
        "config_context": {},
        "created": "2019-12-22",
        "last_updated": "2019-12-22T18:27:54.751136Z",
    },
    {
        "id": 21,
        "url": "https://netboxdemo.com/api/dcim/devices/21/",
        "display": "DS9_QUARKS_U7",
        "name": "DS9_QUARKS_U7",
        "display_name": "DS9_QUARKS_U7",
        "device_type": {
            "id": 2,
            "url": "https://netboxdemo.com/api/dcim/device-types/2/",
            "display": "CPPA-UDDM-SL-1U-24",
            "manufacturer": {
                "id": 3,
                "url": "https://netboxdemo.com/api/dcim/manufacturers/3/",
                "display": "Commscope",
                "name": "Commscope",
                "slug": "commscope",
            },
            "model": "CPPA-UDDM-SL-1U-24",
            "slug": "cppa-uddm-sl-1u-24",
            "display_name": "Commscope CPPA-UDDM-SL-1U-24",
        },
        "device_role": {
            "id": 4,
            "url": "https://netboxdemo.com/api/dcim/device-roles/4/",
            "display": "Copper Patch Panel",
            "name": "Copper Patch Panel",
            "slug": "copper-patch-panel",
        },
        "tenant": {
            "id": 2,
            "url": "https://netboxdemo.com/api/tenancy/tenants/2/",
            "display": "Bajor",
            "name": "Bajor",
            "slug": "bajor",
        },
        "platform": None,
        "serial": "",
        "asset_tag": None,
        "site": {
            "id": 2,
            "url": "https://netboxdemo.com/api/dcim/sites/2/",
            "display": "DS9",
            "name": "DS9",
            "slug": "ds9",
        },
        "location": {
            "id": 2,
            "url": "https://netboxdemo.com/api/dcim/locations/2/",
            "display": "DS9_IDFs",
            "name": "DS9_IDFs",
            "slug": "ds9_idfs",
            "_depth": 0,
        },
        "rack": {
            "id": 3,
            "url": "https://netboxdemo.com/api/dcim/racks/3/",
            "display": "QUARKS_UNDER_COUNTER",
            "name": "QUARKS_UNDER_COUNTER",
            "display_name": "QUARKS_UNDER_COUNTER",
        },
        "position": 7,
        "face": {"value": "front", "label": "Front"},
        "parent_device": None,
        "status": {"value": "active", "label": "Active"},
        "primary_ip": None,
        "primary_ip4": None,
        "primary_ip6": None,
        "cluster": None,
        "virtual_chassis": None,
        "vc_position": None,
        "vc_priority": None,
        "comments": "",
        "local_context_data": None,
        "tags": [],
        "custom_fields": {},
        "config_context": {},
        "created": "2019-12-22",
        "last_updated": "2019-12-22T18:30:02.562910Z",
    },
    {
        "id": 26,
        "url": "https://netboxdemo.com/api/dcim/devices/26/",
        "display": "DS9_SECOFFICE_ACCESS",
        "name": "DS9_SECOFFICE_ACCESS",
        "display_name": "DS9_SECOFFICE_ACCESS",
        "device_type": {
            "id": 4,
            "url": "https://netboxdemo.com/api/dcim/device-types/4/",
            "display": "WS-C3850-48U",
            "manufacturer": {
                "id": 2,
                "url": "https://netboxdemo.com/api/dcim/manufacturers/2/",
                "display": "Cisco",
                "name": "Cisco",
                "slug": "cisco",
            },
            "model": "WS-C3850-48U",
            "slug": "ws-c3850-48u",
            "display_name": "Cisco WS-C3850-48U",
        },
        "device_role": {
            "id": 2,
            "url": "https://netboxdemo.com/api/dcim/device-roles/2/",
            "display": "Access Switch",
            "name": "Access Switch",
            "slug": "access-switch",
        },
        "tenant": {
            "id": 2,
            "url": "https://netboxdemo.com/api/tenancy/tenants/2/",
            "display": "Bajor",
            "name": "Bajor",
            "slug": "bajor",
        },
        "platform": None,
        "serial": "",
        "asset_tag": None,
        "site": {
            "id": 2,
            "url": "https://netboxdemo.com/api/dcim/sites/2/",
            "display": "DS9",
            "name": "DS9",
            "slug": "ds9",
        },
        "location": {
            "id": 2,
            "url": "https://netboxdemo.com/api/dcim/locations/2/",
            "display": "DS9_IDFs",
            "name": "DS9_IDFs",
            "slug": "ds9_idfs",
            "_depth": 0,
        },
        "rack": {
            "id": 6,
            "url": "https://netboxdemo.com/api/dcim/racks/6/",
            "display": "ODO_SEC_OFFICE",
            "name": "ODO_SEC_OFFICE",
            "display_name": "ODO_SEC_OFFICE",
        },
        "position": 5,
        "face": {"value": "front", "label": "Front"},
        "parent_device": None,
        "status": {"value": "active", "label": "Active"},
        "primary_ip": None,
        "primary_ip4": None,
        "primary_ip6": None,
        "cluster": None,
        "virtual_chassis": None,
        "vc_position": None,
        "vc_priority": None,
        "comments": "",
        "local_context_data": None,
        "tags": [],
        "custom_fields": {},
        "config_context": {},
        "created": "2019-12-22",
        "last_updated": "2019-12-22T18:49:00.864058Z",
    },
    {
        "id": 16,
        "url": "https://netboxdemo.com/api/dcim/devices/16/",
        "display": "DS9_SECOFFICE_FIBER_U12",
        "name": "DS9_SECOFFICE_FIBER_U12",
        "display_name": "DS9_SECOFFICE_FIBER_U12",
        "device_type": {
            "id": 1,
            "url": "https://netboxdemo.com/api/dcim/device-types/1/",
            "display": "760231449 | SD-1U",
            "manufacturer": {
                "id": 3,
                "url": "https://netboxdemo.com/api/dcim/manufacturers/3/",
                "display": "Commscope",
                "name": "Commscope",
                "slug": "commscope",
            },
            "model": "760231449 | SD-1U",
            "slug": "760231449-sd-1u",
            "display_name": "Commscope 760231449 | SD-1U",
        },
        "device_role": {
            "id": 5,
            "url": "https://netboxdemo.com/api/dcim/device-roles/5/",
            "display": "Fiber Patch Panel",
            "name": "Fiber Patch Panel",
            "slug": "fiber-patch-panel",
        },
        "tenant": {
            "id": 2,
            "url": "https://netboxdemo.com/api/tenancy/tenants/2/",
            "display": "Bajor",
            "name": "Bajor",
            "slug": "bajor",
        },
        "platform": None,
        "serial": "",
        "asset_tag": None,
        "site": {
            "id": 2,
            "url": "https://netboxdemo.com/api/dcim/sites/2/",
            "display": "DS9",
            "name": "DS9",
            "slug": "ds9",
        },
        "location": {
            "id": 2,
            "url": "https://netboxdemo.com/api/dcim/locations/2/",
            "display": "DS9_IDFs",
            "name": "DS9_IDFs",
            "slug": "ds9_idfs",
            "_depth": 0,
        },
        "rack": {
            "id": 6,
            "url": "https://netboxdemo.com/api/dcim/racks/6/",
            "display": "ODO_SEC_OFFICE",
            "name": "ODO_SEC_OFFICE",
            "display_name": "ODO_SEC_OFFICE",
        },
        "position": 12,
        "face": {"value": "front", "label": "Front"},
        "parent_device": None,
        "status": {"value": "active", "label": "Active"},
        "primary_ip": None,
        "primary_ip4": None,
        "primary_ip6": None,
        "cluster": None,
        "virtual_chassis": None,
        "vc_position": None,
        "vc_priority": None,
        "comments": "",
        "local_context_data": None,
        "tags": [],
        "custom_fields": {},
        "config_context": {},
        "created": "2019-12-22",
        "last_updated": "2019-12-22T18:24:51.431344Z",
    },
    {
        "id": 18,
        "url": "https://netboxdemo.com/api/dcim/devices/18/",
        "display": "DS9_SECOFFICE_PDU",
        "name": "DS9_SECOFFICE_PDU",
        "display_name": "DS9_SECOFFICE_PDU",
        "device_type": {
            "id": 5,
            "url": "https://netboxdemo.com/api/dcim/device-types/5/",
            "display": "PDU1230",
            "manufacturer": {
                "id": 4,
                "url": "https://netboxdemo.com/api/dcim/manufacturers/4/",
                "display": "Tripp Lite",
                "name": "Tripp Lite",
                "slug": "tripp-lite",
            },
            "model": "PDU1230",
            "slug": "pdu1230",
            "display_name": "Tripp Lite PDU1230",
        },
        "device_role": {
            "id": 6,
            "url": "https://netboxdemo.com/api/dcim/device-roles/6/",
            "display": "PDU",
            "name": "PDU",
            "slug": "pdu",
        },
        "tenant": {
            "id": 2,
            "url": "https://netboxdemo.com/api/tenancy/tenants/2/",
            "display": "Bajor",
            "name": "Bajor",
            "slug": "bajor",
        },
        "platform": None,
        "serial": "",
        "asset_tag": None,
        "site": {
            "id": 2,
            "url": "https://netboxdemo.com/api/dcim/sites/2/",
            "display": "DS9",
            "name": "DS9",
            "slug": "ds9",
        },
        "location": {
            "id": 2,
            "url": "https://netboxdemo.com/api/dcim/locations/2/",
            "display": "DS9_IDFs",
            "name": "DS9_IDFs",
            "slug": "ds9_idfs",
            "_depth": 0,
        },
        "rack": {
            "id": 6,
            "url": "https://netboxdemo.com/api/dcim/racks/6/",
            "display": "ODO_SEC_OFFICE",
            "name": "ODO_SEC_OFFICE",
            "display_name": "ODO_SEC_OFFICE",
        },
        "position": 1,
        "face": {"value": "front", "label": "Front"},
        "parent_device": None,
        "status": {"value": "active", "label": "Active"},
        "primary_ip": None,
        "primary_ip4": None,
        "primary_ip6": None,
        "cluster": None,
        "virtual_chassis": None,
        "vc_position": None,
        "vc_priority": None,
        "comments": "",
        "local_context_data": None,
        "tags": [],
        "custom_fields": {},
        "config_context": {},
        "created": "2019-12-22",
        "last_updated": "2019-12-22T18:26:49.236315Z",
    },
    {
        "id": 20,
        "url": "https://netboxdemo.com/api/dcim/devices/20/",
        "display": "DS9_SECOFFICE_U11",
        "name": "DS9_SECOFFICE_U11",
        "display_name": "DS9_SECOFFICE_U11",
        "device_type": {
            "id": 2,
            "url": "https://netboxdemo.com/api/dcim/device-types/2/",
            "display": "CPPA-UDDM-SL-1U-24",
            "manufacturer": {
                "id": 3,
                "url": "https://netboxdemo.com/api/dcim/manufacturers/3/",
                "display": "Commscope",
                "name": "Commscope",
                "slug": "commscope",
            },
            "model": "CPPA-UDDM-SL-1U-24",
            "slug": "cppa-uddm-sl-1u-24",
            "display_name": "Commscope CPPA-UDDM-SL-1U-24",
        },
        "device_role": {
            "id": 4,
            "url": "https://netboxdemo.com/api/dcim/device-roles/4/",
            "display": "Copper Patch Panel",
            "name": "Copper Patch Panel",
            "slug": "copper-patch-panel",
        },
        "tenant": {
            "id": 2,
            "url": "https://netboxdemo.com/api/tenancy/tenants/2/",
            "display": "Bajor",
            "name": "Bajor",
            "slug": "bajor",
        },
        "platform": None,
        "serial": "",
        "asset_tag": None,
        "site": {
            "id": 2,
            "url": "https://netboxdemo.com/api/dcim/sites/2/",
            "display": "DS9",
            "name": "DS9",
            "slug": "ds9",
        },
        "location": {
            "id": 2,
            "url": "https://netboxdemo.com/api/dcim/locations/2/",
            "display": "DS9_IDFs",
            "name": "DS9_IDFs",
            "slug": "ds9_idfs",
            "_depth": 0,
        },
        "rack": {
            "id": 6,
            "url": "https://netboxdemo.com/api/dcim/racks/6/",
            "display": "ODO_SEC_OFFICE",
            "name": "ODO_SEC_OFFICE",
            "display_name": "ODO_SEC_OFFICE",
        },
        "position": 11,
        "face": {"value": "front", "label": "Front"},
        "parent_device": None,
        "status": {"value": "active", "label": "Active"},
        "primary_ip": None,
        "primary_ip4": None,
        "primary_ip6": None,
        "cluster": None,
        "virtual_chassis": None,
        "vc_position": None,
        "vc_priority": None,
        "comments": "",
        "local_context_data": None,
        "tags": [],
        "custom_fields": {},
        "config_context": {},
        "created": "2019-12-22",
        "last_updated": "2019-12-22T18:29:27.279793Z",
    },
]
